name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your preferred Python version

      - name: Install uv
        run: python -m pip install uv # Installs the latest stable version of uv
        # For more reproducibility, you can pin the version, e.g.:
        # run: python -m pip install uv==0.2.3 # Replace with a specific recent version

      # Cache for uv downloaded packages
      - name: Get uv cache directory
        id: get-uv-cache-dir # Step ID to reference its output
        run: echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT

      - name: Cache uv global packages
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-uv-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }} # Add uv.lock if you use it
          restore-keys: |
            ${{ runner.os }}-uv-

      # Cache for MkDocs build artifacts
      - name: Create cache ID for MkDocs
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache MkDocs build artifacts
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache # Default MkDocs cache directory with mkdocs-material
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies from pyproject.toml using uv
        # The --system flag installs into the Python environment set up by actions/setup-python
        run: uv pip install --system .
        # If you generate a lock file (e.g., uv.lock):
        # run: uv pip sync --system --locked uv.lock

      - name: Build and deploy MkDocs site
        run: mkdocs gh-deploy --force
